export const ADD_INGRIDIENTS= 'ADD_INGRIDIENTS';
export const REMOVE_INGRIDIENTS='REMOVE_INGRIDIENTS';
export const SET_INGRIDIENTS='SET_INGRIDIENTS';
export const FETCH_INGRIDIENTS_FAILED='FETCH_INGRIDIENTS_FAILED';


export const PURCHASE_BURGER_SUCCESS='PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL='PURCHASE_BURGER_FAIL';
export const PURCHASE_BURGER_START='PURCHASE_BURGER_START';
export const PURCHASE_INIT='PURCHASE_INIT';
export const GET_ORDERS_START='GET_ORDERS_START';
export const GET_ORDERS_SUCCESS='GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAIL='GET_ORDERS_FAIL';



